### ISSUE TITLE
Navigating to System -> All Users Grid.

### ISSUE THREAD

**Issue by xpec-jalvarez** [cadencelabs/cadence-heimdall#1]
Hi thanks a lot for the module it's really good. I have this problem when i go to Navigate to System -> All Users Grid.

I'm using
Magento 2.1.9
PHP 7.0.22-0ubuntu0.16.04.1 (cli) ( NTS )

`1 exception(s):
Exception #0 (InvalidArgumentException): Frame callback host must be instance of Magento\Backend\Block\Widget

Exception #0 (InvalidArgumentException): Frame callback host must be instance of Magento\Backend\Block\Widget
#0 /var/www/html/xpec/rtc_ecommerce/vendor/magento/module-backend/Block/Widget/Grid/Column.php(291): Magento\Backend\Block\Widget\Grid\Column->validateFrameCallback(Array)
#1 /var/www/html/xpec/rtc_ecommerce/vendor/magento/framework/Interception/Interceptor.php(146): Magento\Backend\Block\Widget\Grid\Column->getRowField(Object(Magento\User\Model\User\Interceptor))
#2 /var/www/html/xpec/rtc_ecommerce/var/generation/Magento/Backend/Block/Widget/Grid/Column/Interceptor.php(208): Magento\Backend\Block\Widget\Grid\Column\Interceptor->___callPlugins('getRowField', Array, Array)
#3 /var/www/html/xpec/rtc_ecommerce/vendor/magento/module-backend/view/adminhtml/templates/widget/grid/column_set.phtml(113): Magento\Backend\Block\Widget\Grid\Column\Interceptor->getRowField(Object(Magento\User\Model\User\Interceptor))
#4 /var/www/html/xpec/rtc_ecommerce/vendor/magento/framework/View/TemplateEngine/Php.php(59): include('/var/www/html/x...')
#5 /var/www/html/xpec/rtc_ecommerce/vendor/magento/framework/View/Element/Template.php(255): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\Backend\Block\Widget\Grid\ColumnSet), '/var/www/html/x...', Array)
#6 /var/www/html/xpec/rtc_ecommerce/vendor/magento/framework/View/Element/Template.php(279): Magento\Framework\View\Element\Template->fetchView('/var/www/html/x...')
#7 /var/www/html/xpec/rtc_ecommerce/vendor/magento/framework/View/Element/AbstractBlock.php(659): Magento\Framework\View\Element\Template->_toHtml()
#8 /var/www/html/xpec/rtc_ecommerce/vendor/magento/framework/View/Layout.php(542): Magento\Framework\View\Element\AbstractBlock->toHtml()
#9 /var/www/html/xpec/rtc_ecommerce/vendor/magento/framework/View/Layout.php(518): Magento\Framework\View\Layout->_renderBlock('permission.user...')
#10 /var/www/html/xpec/rtc_ecommerce/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('permission.user...')
#11 /var/www/html/xpec/rtc_ecommerce/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('permission.user...')
#12 /var/www/html/xpec/rtc_ecommerce/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('permission.user...', true)
#13 /var/www/html/xpec/rtc_ecommerce/vendor/magento/framework/View/Element/AbstractBlock.php(499): Magento\Framework\View\Layout\Interceptor->renderElement('permission.user...', true)
#14 /var/www/html/xpec/rtc_ecommerce/vendor/magento/module-backend/view/adminhtml/templates/widget/grid.phtml(133): Magento\Framework\View\Element\AbstractBlock->getChildHtml('grid.columnSet')
#15 /var/www/html/xpec/rtc_ecommerce/vendor/magento/framework/View/TemplateEngine/Php.php(59): include('/var/www/html/x...')
#16 /var/www/html/xpec/rtc_ecommerce/vendor/magento/framework/View/Element/Template.php(255): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\Backend\Block\Widget\Grid), '/var/www/html/x...', Array)
#17 /var/www/html/xpec/rtc_ecommerce/vendor/magento/framework/View/Element/Template.php(279): Magento\Framework\View\Element\Template->fetchView('/var/www/html/x...')
#18 /var/www/html/xpec/rtc_ecommerce/vendor/magento/module-backend/Block/Template.php(104): Magento\Framework\View\Element\Template->_toHtml()
#19 /var/www/html/xpec/rtc_ecommerce/vendor/magento/framework/View/Element/AbstractBlock.php(659): Magento\Backend\Block\Template->_toHtml()
#20 /var/www/html/xpec/rtc_ecommerce/vendor/magento/framework/View/Layout.php(542): Magento\Framework\View\Element\AbstractBlock->toHtml()
#21 /var/www/html/xpec/rtc_ecommerce/vendor/magento/framework/View/Layout.php(518): Magento\Framework\View\Layout->_renderBlock('adminhtml.user....')
#22 /var/www/html/xpec/rtc_ecommerce/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('adminhtml.user....')
#23 /var/www/html/xpec/rtc_ecommerce/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('adminhtml.user....')
#24 /var/www/html/xpec/rtc_ecommerce/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('adminhtml.user....', true)
#25 /var/www/html/xpec/rtc_ecommerce/vendor/magento/framework/View/Element/AbstractBlock.php(499): Magento\Framework\View\Layout\Interceptor->renderElement('adminhtml.user....', true)
#26 /var/www/html/xpec/rtc_ecommerce/vendor/magento/module-backend/Block/Widget/Grid/Container.php(118): Magento\Framework\View\Element\AbstractBlock->getChildHtml('grid')
#27 /var/www/html/xpec/rtc_ecommerce/vendor/magento/module-backend/view/adminhtml/templates/widget/grid/container.phtml(13): Magento\Backend\Block\Widget\Grid\Container->getGridHtml()
#28 /var/www/html/xpec/rtc_ecommerce/vendor/magento/framework/View/TemplateEngine/Php.php(59): include('/var/www/html/x...')
#29 /var/www/html/xpec/rtc_ecommerce/vendor/magento/framework/View/Element/Template.php(255): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\User\Block\User), '/var/www/html/x...', Array)
#30 /var/www/html/xpec/rtc_ecommerce/vendor/magento/framework/View/Element/Template.php(279): Magento\Framework\View\Element\Template->fetchView('/var/www/html/x...')
#31 /var/www/html/xpec/rtc_ecommerce/vendor/magento/module-backend/Block/Template.php(104): Magento\Framework\View\Element\Template->_toHtml()
#32 /var/www/html/xpec/rtc_ecommerce/vendor/magento/framework/View/Element/AbstractBlock.php(659): Magento\Backend\Block\Template->_toHtml()
#33 /var/www/html/xpec/rtc_ecommerce/vendor/magento/framework/View/Layout.php(542): Magento\Framework\View\Element\AbstractBlock->toHtml()
#34 /var/www/html/xpec/rtc_ecommerce/vendor/magento/framework/View/Layout.php(518): Magento\Framework\View\Layout->_renderBlock('adminhtml.user....')
#35 /var/www/html/xpec/rtc_ecommerce/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('adminhtml.user....')
#36 /var/www/html/xpec/rtc_ecommerce/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('adminhtml.user....')
#37 /var/www/html/xpec/rtc_ecommerce/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('adminhtml.user....', true)
#38 /var/www/html/xpec/rtc_ecommerce/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('adminhtml.user....')
#39 /var/www/html/xpec/rtc_ecommerce/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('content')
#40 /var/www/html/xpec/rtc_ecommerce/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('content')
#41 /var/www/html/xpec/rtc_ecommerce/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('content')
#42 /var/www/html/xpec/rtc_ecommerce/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('content', true)
#43 /var/www/html/xpec/rtc_ecommerce/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('content')
#44 /var/www/html/xpec/rtc_ecommerce/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('main.col')
#45 /var/www/html/xpec/rtc_ecommerce/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('main.col')
#46 /var/www/html/xpec/rtc_ecommerce/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('main.col')
#47 /var/www/html/xpec/rtc_ecommerce/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('main.col', true)
#48 /var/www/html/xpec/rtc_ecommerce/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('main.col')
#49 /var/www/html/xpec/rtc_ecommerce/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('admin.scope.col...')
#50 /var/www/html/xpec/rtc_ecommerce/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('admin.scope.col...')
#51 /var/www/html/xpec/rtc_ecommerce/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('admin.scope.col...')
#52 /var/www/html/xpec/rtc_ecommerce/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('admin.scope.col...', true)
#53 /var/www/html/xpec/rtc_ecommerce/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('admin.scope.col...')
#54 /var/www/html/xpec/rtc_ecommerce/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('page.main.conta...')
#55 /var/www/html/xpec/rtc_ecommerce/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('page.main.conta...')
#56 /var/www/html/xpec/rtc_ecommerce/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('page.main.conta...')
#57 /var/www/html/xpec/rtc_ecommerce/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('page.main.conta...', true)
#58 /var/www/html/xpec/rtc_ecommerce/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('page.main.conta...')
#59 /var/www/html/xpec/rtc_ecommerce/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('page.content')
#60 /var/www/html/xpec/rtc_ecommerce/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('page.content')
#61 /var/www/html/xpec/rtc_ecommerce/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('page.content')
#62 /var/www/html/xpec/rtc_ecommerce/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('page.content', true)
#63 /var/www/html/xpec/rtc_ecommerce/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('page.content')
#64 /var/www/html/xpec/rtc_ecommerce/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('page.wrapper')
#65 /var/www/html/xpec/rtc_ecommerce/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('page.wrapper')
#66 /var/www/html/xpec/rtc_ecommerce/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('page.wrapper')
#67 /var/www/html/xpec/rtc_ecommerce/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('page.wrapper', true)
#68 /var/www/html/xpec/rtc_ecommerce/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('page.wrapper')
#69 /var/www/html/xpec/rtc_ecommerce/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('backend.page')
#70 /var/www/html/xpec/rtc_ecommerce/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('backend.page')
#71 /var/www/html/xpec/rtc_ecommerce/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('backend.page')
#72 /var/www/html/xpec/rtc_ecommerce/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('backend.page', true)
#73 /var/www/html/xpec/rtc_ecommerce/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('backend.page')
#74 /var/www/html/xpec/rtc_ecommerce/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('root')
#75 /var/www/html/xpec/rtc_ecommerce/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('root')
#76 /var/www/html/xpec/rtc_ecommerce/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('root')
#77 /var/www/html/xpec/rtc_ecommerce/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('root', true)
#78 /var/www/html/xpec/rtc_ecommerce/vendor/magento/framework/View/Layout.php(938): Magento\Framework\View\Layout\Interceptor->renderElement('root')
#79 /var/www/html/xpec/rtc_ecommerce/var/generation/Magento/Framework/View/Layout/Interceptor.php(492): Magento\Framework\View\Layout->getOutput()
#80 /var/www/html/xpec/rtc_ecommerce/vendor/magento/framework/View/Result/Page.php(243): Magento\Framework\View\Layout\Interceptor->getOutput()
#81 /var/www/html/xpec/rtc_ecommerce/vendor/magento/framework/View/Result/Layout.php(164): Magento\Framework\View\Result\Page->render(Object(Magento\Framework\App\Response\Http\Interceptor))
#82 /var/www/html/xpec/rtc_ecommerce/var/generation/Magento/Backend/Model/View/Result/Page/Interceptor.php(193): Magento\Framework\View\Result\Layout->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#83 /var/www/html/xpec/rtc_ecommerce/vendor/magento/framework/App/View.php(221): Magento\Backend\Model\View\Result\Page\Interceptor->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#84 /var/www/html/xpec/rtc_ecommerce/vendor/magento/module-user/Controller/Adminhtml/User/Index.php(18): Magento\Framework\App\View->renderLayout()
#85 /var/www/html/xpec/rtc_ecommerce/var/generation/Magento/User/Controller/Adminhtml/User/Index/Interceptor.php(24): Magento\User\Controller\Adminhtml\User\Index->execute()
#86 /var/www/html/xpec/rtc_ecommerce/vendor/magento/framework/App/Action/Action.php(102): Magento\User\Controller\Adminhtml\User\Index\Interceptor->execute()
#87 /var/www/html/xpec/rtc_ecommerce/vendor/magento/module-backend/App/AbstractAction.php(226): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#88 /var/www/html/xpec/rtc_ecommerce/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Backend\App\AbstractAction->dispatch(Object(Magento\Framework\App\Request\Http))
#89 /var/www/html/xpec/rtc_ecommerce/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\User\Controller\Adminhtml\User\Index\Interceptor->___callParent('dispatch', Array)
#90 /var/www/html/xpec/rtc_ecommerce/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\User\\Co...', 'dispatch', Object(Magento\User\Controller\Adminhtml\User\Index\Interceptor), Array, 'adminAuthentica...')
#91 /var/www/html/xpec/rtc_ecommerce/vendor/cadence/heimdall/Plugin/Backend/Authentication.php(50): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#92 /var/www/html/xpec/rtc_ecommerce/vendor/magento/framework/Interception/Chain/Chain.php(67): Cadence\Heimdall\Plugin\Backend\Authentication->aroundDispatch(Object(Magento\User\Controller\Adminhtml\User\Index\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#93 /var/www/html/xpec/rtc_ecommerce/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\User\\Co...', 'dispatch', Object(Magento\User\Controller\Adminhtml\User\Index\Interceptor), Array, 'adminMassaction...')
#94 /var/www/html/xpec/rtc_ecommerce/vendor/magento/module-backend/App/Action/Plugin/MassactionKey.php(33): Magento\User\Controller\Adminhtml\User\Index\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#95 /var/www/html/xpec/rtc_ecommerce/vendor/magento/framework/Interception/Interceptor.php(142): Magento\Backend\App\Action\Plugin\MassactionKey->aroundDispatch(Object(Magento\User\Controller\Adminhtml\User\Index\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#96 /var/www/html/xpec/rtc_ecommerce/var/generation/Magento/User/Controller/Adminhtml/User/Index/Interceptor.php(39): Magento\User\Controller\Adminhtml\User\Index\Interceptor->___callPlugins('dispatch', Array, Array)
#97 /var/www/html/xpec/rtc_ecommerce/vendor/magento/framework/App/FrontController.php(55): Magento\User\Controller\Adminhtml\User\Index\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#98 /var/www/html/xpec/rtc_ecommerce/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#99 /var/www/html/xpec/rtc_ecommerce/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#100 /var/www/html/xpec/rtc_ecommerce/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'install')
#101 /var/www/html/xpec/rtc_ecommerce/vendor/magento/framework/Module/Plugin/DbStatusValidator.php(69): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#102 /var/www/html/xpec/rtc_ecommerce/vendor/magento/framework/Interception/Interceptor.php(142): Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#103 /var/www/html/xpec/rtc_ecommerce/var/generation/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#104 /var/www/html/xpec/rtc_ecommerce/vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#105 /var/www/html/xpec/rtc_ecommerce/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#106 /var/www/html/xpec/rtc_ecommerce/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#107 {main}`

**Comment by chtekock** [comment]
The same here on magento 2.2

**Comment by chtekock** [comment]
same here on magento 2.2

**Comment by intelsteel** [comment]
Any Update about this issue ?
Am getting it on magento 2.2.3 on user edit screen, but not on all users.

**Comment by intelsteel** [comment]
Any Update ?
Am asking this from last 2 weeks !!!
